# Generated by Django 3.2.13 on 2023-01-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230116_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified_email',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
