repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/google/yapf
    rev: v0.33.0
    hooks:
        - id: yapf
          args: [
            '--style={
                 based_on_style: pep8,
                 column_limit: 119,
                 align_closing_bracket_with_visual_indent: False,
                 dedent_closing_brackets: True,
                 space_between_ending_comma_and_closing_bracket: False,
                 split_before_expression_after_opening_paren: True,
                 split_complex_comprehension: True,
                 blank_line_before_nested_class_or_def: True,
                 i18n_function_call: ["_"],
            }',
            '--parallel',
            '--in-place',
            '--recursive',
            '--verbose',
          ]
          language_version: python3.11

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--config=.flake8, app]
        additional_dependencies:
          - flake8-bugbear
          - flake8-import-order
          - flake8-docstrings
          - flake8-quotes
          - flake8-commas
          - flake8-builtins
        language_version: python3.11
