version: '3'

services:
  django:
    container_name: local-django
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env.project
    command: sh -c "python app/manage.py migrate && python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/home/app/web/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - celery

  postgres:
    container_name: local-postgres
    image: postgres:15.3
    env_file:
      - env/.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: local-redis
    image: redis:7.0.5-alpine
    hostname: redis

  celery:
    container_name: local-celery
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env.project
    environment:
      - REDIS_HOST=redis
    entrypoint: celery
    command: --workdir=./app -A config worker --loglevel=info
    volumes:
      - .:/home/app/web/
    depends_on:
      - redis

  stripe:
    container_name: local-stripe
    image: stripe/stripe-cli:v1.14.7
    command: listen --forward-to 127.0.0.1:8000/webhook/stripe/
    depends_on:
      - django

volumes:
  postgres_data:
