version: '3'

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/.env
    command: sh -c "python app/manage.py migrate && python app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - celery

  postgres:
    container_name: postgres
    image: postgres:15.3
    env_file:
      - env/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    hostname: redis

  celery:
    container_name: celery
    build:
      context: .
    env_file:
      - env/.env
    environment:
      - REDIS_HOST=redis
    entrypoint: celery
    command: -A config.celery.app worker --loglevel=info
    volumes:
      - ./app:/app
    depends_on:
      - redis

volumes:
  postgres_data:
