version: '3'

services:
  django:
    container_name: django3-python3.11
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --chdir app config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - env/.env
    volumes:
      - app:/home/app/web
    depends_on:
      - postgres
      - redis
      - celery

  postgres:
    container_name: postgres-15.3
    image: postgres:15.3
    env_file:
      - env/.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: redis-7.0.5
    image: redis:7.0.5-alpine
    hostname: redis

  celery:
    container_name: celery_worker-5.2.7
    build:
      context: .
    env_file:
      - env/.env
    environment:
      - REDIS_HOST=redis
    entrypoint: celery
    command: --workdir=./app -A config worker --loglevel=info
    depends_on:
      - redis

  nginx:
    container_name: nginx-1.25
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:333"
    volumes:
      - app:/home/app/web
      - ./nginx-conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - django

  certbot:
    container_name: certbot
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot


volumes:
  app:
  postgres_data:
