# Generated by Django 3.2.18 on 2023-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('address', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('PAID', 'Оплачен'), ('ON_WAY', 'В пути'), ('DELIVERED', 'Доставлен')], default='CREATED', max_length=22)),
                ('basket_history', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
