name: Basic code style checks

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Update pip and Install poetry
        run:  |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Poetry activate shell
        run: poetry shell

      - name: Poetry install
        run: poetry install

      - name: Run django tests
        run: python app/manage.py test
